"""Selects the study universe from train-day statistics only (apps/day_stats output).

Rule, fixed before looking at validation or test days:
- present on every train day, not an ETP, mean mid at least $5, two-sided quotes for at
  least 99% of regular hours on every train day;
- large-tick: spread of one tick for at least half of the time (mean over train days);
  small-tick: mean time-weighted spread of at least three ticks;
- the 25 largest of each group by mean Nasdaq traded notional, plus SPY and QQQ.

Usage: python research/universe.py <train-day.tsv> ... > configs/universe.toml
"""

import sys

import polars as pl

N_PER_GROUP = 25


def main():
    paths = sys.argv[1:]
    days = [pl.read_csv(p, separator="\t").with_columns(pl.lit(i).alias("day"))
            for i, p in enumerate(paths)]
    df = pl.concat(days)
    agg = (df.group_by("symbol")
             .agg(pl.len().alias("n_days"),
                  pl.col("etp").first(),
                  pl.col("notional").mean(),
                  pl.col("spread_ticks").mean(),
                  pl.col("one_tick_share").mean(),
                  pl.col("mid").mean(),
                  pl.col("two_sided_share").min()))
    ok = agg.filter((pl.col("n_days") == len(paths)) & (pl.col("etp") == "N") &
                    (pl.col("mid") >= 5) & (pl.col("two_sided_share") >= 0.99))
    large = ok.filter(pl.col("one_tick_share") >= 0.5).sort("notional", descending=True).head(N_PER_GROUP)
    small = ok.filter(pl.col("spread_ticks") >= 3).sort("notional", descending=True).head(N_PER_GROUP)
    index = agg.filter(pl.col("symbol").is_in(["SPY", "QQQ"])).sort("symbol")

    print("# Study universe. Generated by research/universe.py from train days only:")
    for p in paths:
        print(f"#   {p.rsplit('/', 1)[-1]}")
    print("# Columns: mean notional ($), mean spread (ticks), one-tick share, mean mid ($).\n")
    for name, group in (("large_tick", large), ("small_tick", small), ("index", index)):
        print(f"[{name}]")
        print("symbols = [" + ", ".join(f'"{s}"' for s in group["symbol"]) + "]")
        for r in group.iter_rows(named=True):
            print(f"# {r['symbol']:<6} {r['notional']:>15,.0f} {r['spread_ticks']:7.3f} "
                  f"{r['one_tick_share']:6.3f} {r['mid']:9.2f}")
        print()


if __name__ == "__main__":
    main()
